# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.2.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ricky
      MONGO_INITDB_ROOT_PASSWORD: imRicky

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ricky
      ME_CONFIG_MONGODB_ADMINPASSWORD: imRicky